### ISSUE TITLE
Can't get nexus3 to start with this

### ISSUE THREAD

**Issue by klevermonicker** [auchanretailfrance/nexus3-gitlabauth-plugin#1]
I need to get gitlab oauth working with nexus and thank you for writing this plugin! Second, Followed your instructions and I am unable to get this to work.

I'm getting this:
```
SEVERE: Could not launch framework
java.lang.RuntimeException: Error installing bundle listed in startup.properties with url: mvn:fr.auchan/nexus3-gitlabauth-plugin/1.1.0 and startlevel: 200
        at org.apache.karaf.main.Main.installAndStartBundles(Main.java:495)
        at org.apache.karaf.main.Main.launch(Main.java:311)
        at org.sonatype.nexus.karaf.NexusMain.launch(NexusMain.java:106)
        at org.sonatype.nexus.karaf.NexusMain.main(NexusMain.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62)
        at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:60)
Caused by: java.lang.RuntimeException: Could not resolve mvn:fr.auchan/nexus3-gitlabauth-plugin/1.1.0
        at org.apache.karaf.main.util.SimpleMavenResolver.resolve(SimpleMavenResolver.java:59)
        at org.apache.karaf.main.Main.installAndStartBundles(Main.java:487)
        ... 9 more
```

I'm not entirely sure what I'm missing here, I'm not a java/maven guy...

Let me know if I can get you more information.

Nexus Version: 3.11.0-01
JVM: java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

Ubuntu 16

**Comment by klevermonicker** [comment]
Going to close this.

The instructions in the readme weren't 100% coorect for the path outside of docker. I can't speak to docker. I changed the maven path inside of /opt/sonatype/nexus/etc/karaf/startup.properties to read this:

mvn\:fr.auchan/nexus3-gitlabauth-plugin/1.1.0

this allowed nexus to start without any errors.

**Comment by khalith** [comment]
@klevermonicker Can you please let us know what you have changed inside /opt/sonatype/nexus/etc/karaf/startup.properties, so that others also make use of the change. I know instruction on readme is not correct.
